version: '3'

networks:
  asa:
    driver: bridge

services:
  
  web01:
    build:
      context: ./web01
      dockerfile: Dockerfile.dockerfile
    image: web01
    container_name: web01
    restart: always
    tty: true
    networks:
      - asa
  
  web02:
    build:
      context: ./web02
      dockerfile: Dockerfile.dockerfile
    image: web02
    container_name: web02
    restart: always
    tty: true
    networks:
      - asa

  web03:
    build:
      context: ./web03
      dockerfile: Dockerfile.dockerfile
    image: web03
    container_name: web03
    restart: always
    tty: true
    networks:
      - asa
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dockerfile
    image: proxy
    container_name: proxy
    hostname: www.asa.br
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - asa

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile.dockerfile
    image: dns
    container_name: dns
    hostname: ns1.asa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./dns/conf:/etc/bind
    networks:
      - asa
        
  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: email
    container_name: email
    hostname: mail.asa.br
    restart: always
    tty: true
    volumes:
      - ./conf-email/rainloop:/var/www/html/rainloop
    ports:
      - "2525:25/tcp"
      - "100:100/tcp"
      - "143:143/tcp"
      - "587:587/tcp"
      - "993:993/tcp"
      - "995:995/tcp"
    networks:
      - asa